version: '3.8'

services:
  earnings-rag-app:
    build: .
    ports:
      - "8501:8501"    # Streamlit
      - "11434:11434"  # Ollama
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_HOST=http://localhost:11434
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Redis for caching (if needed for scaling)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - with-redis

volumes:
  ollama_models:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: earnings-rag-network
